dist: bionic
language: bash
services:
  - docker
jobs:
  include:
    - stage: "Building Docker Images"
      name: "Kernel Image"
      script:
      - echo "Kernel Image Here"
      name: "Build Tools"
      script:
      - docker build -f Dockerfile_Kernel -t crazyuploader/build_tools:latest .
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker images
