dist: focal
language: bash
services:
  - docker
jobs:
  include:
    - stage: "Building Docker Images"
      name: "Kernel Builder"
      script:
        - docker build -f kernel_build/Dockerfile -t crazyuploader/kernel_build:latest .
        - docker images

    - name: "Python Build Tools"
      script:
        - docker build -f python_build_tools/Dockerfile -t crazyuploader/python_build_tools:latest .
        - docker images

    - name: "Java Build Tools"
      script:
        - docker build -f java_build_tools/Dockerfile -t crazyuploader/java_build_tools:latest .
        - docker images

    - name: "Android SDK"
      script:
        - docker build -f android_sdk/Dockerfile -t crazyuploader/android_sdk:latest .
        - docker images

    - name: "Android SDK with Flutter"
      script:
        - docker build -f android_sdk_flutter/Dockerfile -t crazyuploader/android_sdk_flutter:latest .
        - docker images

    - name: "CPP & C Build Tools"
      script:
        - docker build -f cpp_build_tools/Dockerfile -t crazyuploader/cpp_build_tools:latest .
        - docker images

    - name: "NodeJS Build Tools"
      script:
        - docker build -f node_build_tools/Dockerfile -t crazyuploader/node_build_tools:latest .
        - docker images

    - name: "Minimal Ubuntu"
      script:
        - docker build -f minimal_ubuntu/Dockerfile -t crazyuploader/minimal_ubuntu:latest .
        - docker images

    - name: "Hugo Site Generator"
      script:
        - docker build -f minimal_ubuntu/Dockerfile -t crazyuploader/hugo:latest .
        - docker images

    - name: "Speedtest"
      script:
        - docker build -f minimal_ubuntu/Dockerfile -t crazyuploader/speedtest:latest .
        - docker images
