dist: bionic
language: bash
services:
  - docker
before_script:
  - docker build -t crazyuploader/kernel:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - docker images
  - docker push crazyuploader/kernel
