#
# Jugal Kishore -- 2020
#
# All the required tools for coding and stuff
#
# Base Image: Ubuntu
FROM ubuntu:rolling

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get -y autoremove
RUN apt-get install -y git curl python3 python3-pip clang g++ wget nano
RUN pip3 --version
