version: 2.1
jobs:
  build-amd64:
    machine:
      image: default
    steps:
      - checkout
      - run:
          name: Building Changed Dockerfile(s)
          command: |
            bash test.sh

  build-arm64:
    machine:
      image: default
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Building Dockerfile(s) on arm64
          command: |
            bash test.sh

workflows:
  build:
    jobs:
      - build-amd64
      - build-arm64
