version: 2.1
jobs:
  build-amd64:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: Building Changed Dockerfile(s)
          command: |
            bash test.sh

  build-arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Building Dockerfile(s) on arm64
          command: |
            set -x
            for dockerfile in $(cat arm64.list); do
                echo ""
                echo "Building --> ${dockerfile}/Dockerfile"
                echo ""
                docker build --file ${dockerfile}/Dockerfile --tag crazyuploader/${dockerfile}:arm64 .
            done
            docker images

workflows:
  build:
    jobs:
      - build-amd64
      - build-arm64
