name: Docker Image CI

on: [push, pull_request]

jobs:
  Docker_Images_Builder:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: bash test.sh
