name: Docker Image CI

on: [push, pull_request]

jobs:
  Docker_Images_Builder:
    runs-on: ubuntu-latest

    steps:

      -
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      -
        name: Build Dockerfile(s)
        run: docker buildx build --platform linux/amd64,linux/arm64 --file speedtest/Dockerfile --tag crazyuploader/speedtest:latest .
