name: Docker Image CI

on: [push, pull_request]

jobs:
  Docker_Images_Builder:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Changed Dockerfile(s)
        run: bash test.sh
