name: Docker Image CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  Docker_Images_Builder:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        Docker_Image:
          [
            alpine,
            broken_link_checker,
            hugo,
            markdown_server,
            minimal_ubuntu,
            node_build_tools,
            python_build_tools,
            speedtest,
          ]

    steps:
      - uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Dockerfile(s)
        run: docker buildx build --platform linux/amd64,linux/arm64 --file "${{ matrix.Docker_Image }}"/Dockerfile --tag crazyuploader/"${{ matrix.Docker_Image }}":latest --push .
